Proposed edit to CI/CD
DataSentics/odap-framework-demo pull request #18
Opened 2022-11-13 16:22 UTC by fkrjakDatasentics

2022-11-15 13:29 UTC, guderkar requested changes

2022-11-15 13:29 UTC, guderkar commented on _cicd/azure-pipelines.yml
> +            workingDirectory: '$(System.DefaultWorkingDirectory)'
why tag and cluster are defined as devops variables? Why shouldn't we define the whole databricks workflow in yaml/json?

2022-11-15 13:29 UTC, guderkar commented on _cicd/check_config.py
> +            raise Exception
add exception message

2022-11-15 21:17 UTC, fkrjakDatasentics commented on _cicd/check_config.py
> +            raise Exception
added in new commit

2022-11-15 21:18 UTC, fkrjakDatasentics commented on _cicd/azure-pipelines.yml
> +            workingDirectory: '$(System.DefaultWorkingDirectory)'
fixed in commit

2022-11-16 08:43 UTC, guderkar requested changes

2022-11-16 08:43 UTC, guderkar commented on config.yaml
> +      fs.azure.account.oauth2.client.endpoint.odapczlakeg2test.dfs.core.windows.net: "https://login.microsoftonline.com/585127aa-8691-4f25-9777-8cb78ccf0d91/oauth2/token"
We don't need any external storage for demo so this conf is not needed

2022-11-16 08:43 UTC, guderkar commented on config.yaml
> +      TENANT_ID: "585127aa-8691-4f25-9777-8cb78ccf0d91"
Those env vars are also not needed

2022-11-16 08:43 UTC, guderkar commented on config.yaml
> +    instance_pool_id: "0712-081441-voile3-pool-dt4ut8z6"
Don't assume pool will be present, just define classical job cluster instead

2022-11-24 15:06 UTC, guderkar approved these changes

2022-11-24 15:54 UTC, merged